name: Main CI
on:
  push:
    branches: 
      - main
    paths:
      - 'images/**'

concurrency:
  group: main_push_images
  cancel-in-progress: true

jobs:
  push-images:
    uses: ./.github/workflows/reusable_build_images.yml
    with:
      push: true
      is_latest: false
      version: 'main'
    secrets: inherit
